language: node_js

node_js: '8'

jobs: 
  inclde:
    - stage: 'Tests'
      name: 'lint test'
      script: 'npm run lint'
    - stage: 'Build'
      name: 'build choiceJs'
      script: 'npm run build'
      if: brach = /^release[\/_]\d+\.\d+$/

cache: npm