language: node_js

node_js: '8'

stages:
 - test
 - name: deploy

jobs:
 include:
   - stage: test
     script:
       - echo "Testing Started ..."
       - npm run test
       - echo "Testing Finished."

   - stage: deploy
     script:
       - echo "NPM Deploying Started ..."
       - npm version
       - npm run build:deploy
       - echo "NPM Building Finished."

     deploy:
       provider: npm
       email: linyimin520812@gmail.com
       api_key: "$NPM_TOKEN"
       skip_cleanup: true
       on:
          branch: /^release[\/_]\d+\.\d+$/

cache: npm