language: node_js

node_js: 

stages:
- lint
- name: build
  if: branch = /^release[\/_]\d+\.\d+$/

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run lint
    - npm run build

cache: npm