language: node_js

node_js: '8'

jobs: 
  include:
    - stage: 'Tests'
      name: 'lint test'
      script: 'npm run lint'
    - name: 'unit test'
      script: 'npm run test:deploy'
      if: branch = /^release[\/_]\d+\.\d+$/
    - name: 'unit test build'
      script: 'npm run test:build'
      if: branch = master

    - stage: 'Build'
      name: 'build deploy choiceJs'
      script: 'npm run build:deploy'
      if: branch = /^release[\/_]\d+\.\d+$/
    - name: 'build choiceJs'
      script: 'npm run build'
      if: branch = master

    - stage: deploy
      if: branch = /^release[\/_]\d+\.\d+$/

      deploy:
        provider: npm
        email: gosick.but@qq.com
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: /^release[\/_]\d+\.\d+$/

cache: npm